package Vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.Conexion;
import static Controlador.Conexion.getConnection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author felip
 */
public class VentanaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    public Conexion conexi = new Conexion();
    public PreparedStatement ps, ps1;
    public ResultSet rs;
    public DefaultTableModel dft;
    int contador;
    int resultado;
    boolean seCumple;
    boolean passwordVisible = false;

    public VentanaUsuario() {
        initComponents();
        this.setLocation(259, 165);
        //this.setAlwaysOnTop(true);
        mostrarTabla();
        seleccionarTabla();
    }

    private void mostrarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        rs = Conexion.getTabla("select *from usuario");
        //se asignan los nombre de la columna
        modelo.setColumnIdentifiers(new Object[]
        {
            "Usuario", "Nombre", "A. Paterno", "A. Materno", "Contraseña", "Correo", "Rol"
        });

        try
        {
            while (rs.next())
            {
                modelo.addRow(new Object[]
                {
                    rs.getString("cusuario"), rs.getString("nombre"), rs.getString("apellido_paterno"), rs.getString("apellido_materno"), rs.getString("contrasena"), rs.getString("correo_electronico"), rs.getString("tipo_usuario")
                });

            }
            tablaUsuarios.setModel(modelo);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //seleccionarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        bEliminar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cUsuario = new javax.swing.JTextField();
        cNombre = new javax.swing.JTextField();
        cPaterno = new javax.swing.JTextField();
        cMaterno = new javax.swing.JTextField();
        crContrasena = new javax.swing.JPasswordField();
        cContrasena = new javax.swing.JPasswordField();
        cCorreo = new javax.swing.JTextField();
        comboRol = new javax.swing.JComboBox<>();
        bLimpiar = new javax.swing.JButton();
        lblvalido = new javax.swing.JLabel();
        verContra = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(236, 226, 198));

        botonSalir.setBackground(new java.awt.Color(112, 80, 48));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(236, 226, 198));
        jScrollPane1.setToolTipText("");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaUsuarios.setAutoscrolls(false);
        tablaUsuarios.setGridColor(new java.awt.Color(236, 226, 198));
        tablaUsuarios.setRowSelectionAllowed(false);
        tablaUsuarios.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tablaUsuarios.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaUsuarios);

        bEliminar.setBackground(new java.awt.Color(112, 80, 48));
        bEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        botonRegistrar.setBackground(new java.awt.Color(112, 80, 48));
        botonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        bActualizar.setBackground(new java.awt.Color(112, 80, 48));
        bActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bActualizar.setForeground(new java.awt.Color(255, 255, 255));
        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panaderoVentana.png"))); // NOI18N
        jLabel1.setText("Registrar usuarios");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Primer Apellido : ");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Segundo Apellido: ");

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Usuario:");

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contraseña: ");

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Confirmar contraseña: ");

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Correo:");

        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Tipo usuario:");

        cUsuario.setEditable(true);
        cUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cUsuario.setBorder(null);
        cUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cUsuarioMouseMoved(evt);
            }
        });
        cUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioActionPerformed(evt);
            }
        });
        cUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cUsuarioKeyTyped(evt);
            }
        });

        cNombre.setEditable(true);
        cNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cNombre.setBorder(null);
        cNombre.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cNombreMouseMoved(evt);
            }
        });
        cNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNombreActionPerformed(evt);
            }
        });
        cNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNombreKeyTyped(evt);
            }
        });

        cPaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cPaterno.setBorder(null);
        cPaterno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cPaternoMouseMoved(evt);
            }
        });
        cPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPaternoKeyTyped(evt);
            }
        });

        cMaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cMaterno.setBorder(null);
        cMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cMaternoKeyTyped(evt);
            }
        });

        crContrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        crContrasena.setBorder(null);
        crContrasena.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                crContrasenaMouseMoved(evt);
            }
        });
        crContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crContrasenaActionPerformed(evt);
            }
        });

        cContrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cContrasena.setBorder(null);
        cContrasena.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cContrasenaMouseMoved(evt);
            }
        });
        cContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cContrasenaActionPerformed(evt);
            }
        });
        cContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cContrasenaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cContrasenaKeyTyped(evt);
            }
        });

        cCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cCorreo.setBorder(null);
        cCorreo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cCorreoMouseMoved(evt);
            }
        });
        cCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCorreoActionPerformed(evt);
            }
        });

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        comboRol.setSelectedItem(null);
        comboRol.setBorder(null);

        bLimpiar.setBackground(new java.awt.Color(112, 80, 48));
        bLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        lblvalido.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        verContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojo.png"))); // NOI18N
        verContra.setBorder(null);
        verContra.setEnabled(false);
        verContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verContraMouseClicked(evt);
            }
        });
        verContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verContraActionPerformed(evt);
            }
        });

        jLabel10.setText("(A-z, 0-9, #$%!?...)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(bActualizar)
                        .addGap(64, 64, 64)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblvalido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(crContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboRol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                            .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verContra, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(354, 354, 354)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(verContra)
                                .addGap(122, 122, 122)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(cPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblvalido, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(crContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION)
        {
            try
            {
                Conexion con = new Conexion();
                Connection conexion = con.getConnection();
                ps = conexion.prepareStatement("delete from usuario where cusuario=?");
                ps.setString(1, cUsuario.getText());
                int resultado = ps.executeUpdate();
                if (resultado > 0)
                {
                    JOptionPane.showMessageDialog(null, "Eliminacion correcta");
                    mostrarTabla();
                } else
                {
                    JOptionPane.showMessageDialog(null, "No se realizo la eliminación de los datos");
                }
                conexion.close();
            } catch (Exception e)
            {
                System.err.println(e);
            }
            limpiar();
            tablaUsuarios.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);

        } else
        {
            System.out.println("El usuario seleccionó 'No'.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:

        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        String email = cCorreo.getText();
        Matcher mather = pattern.matcher(email);
        if (cUsuario.getText().isEmpty() || cNombre.getText().isEmpty() || cPaterno.getText().isEmpty()
                || cContrasena.getText().isEmpty() || crContrasena.getText().isEmpty() || cCorreo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Existe Algun Campo Vacío", "Error!", JOptionPane.ERROR_MESSAGE);
        } else if (mather.find() == true)
        {
            Connection conexion = null;
            int resultado = 0;
            boolean yaRegistrado;
            try
            {
                conexion = conexi.getConnection();
                ps = conexion.prepareStatement("insert into usuario(cusuario,nombre,apellido_paterno,apellido_materno,contrasena,rcontrasena,correo_electronico,tipo_usuario)values(?,?,?,?,?,?,?,?)");
                ps.setString(1, cUsuario.getText());
                ps.setString(2, cNombre.getText());
                ps.setString(3, cPaterno.getText());
                ps.setString(4, cMaterno.getText());
                ps.setString(5, cContrasena.getText());
                ps.setString(6, crContrasena.getText());
                ps.setString(7, cCorreo.getText());
                ps.setString(8, comboRol.getSelectedItem().toString());

                if (cContrasena.getText().equals(crContrasena.getText()))
                {
                    resultado = ps.executeUpdate(); //ejecutamos la inserccion
                } else
                {
                    JOptionPane.showMessageDialog(null, "Verifique que las contraseñas sean iguales");
                }
                if ((resultado > 0))
                {
                    JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                    limpiar();
                    mostrarTabla();
                } else
                {
                    JOptionPane.showMessageDialog(null, "Verifique que los datos sean correctos");

                }
                conexion.close();

            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Verifique los datos");
            }
            tablaUsuarios.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else
        {
            JOptionPane.showMessageDialog(null, "El email ingresado es inválido.");
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed
    private void limpiar() {
        cNombre.setText("");
        cPaterno.setText("");
        cMaterno.setText("");
        cUsuario.setText("");
        cContrasena.setText("");
        crContrasena.setText("");
        cCorreo.setText("");
        comboRol.setSelectedItem(null);
        tablaUsuarios.setRowSelectionAllowed(false);
        botonRegistrar.setEnabled(true);

    }


    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:

        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        String email = cCorreo.getText();
        Matcher mather = pattern.matcher(email);

        if (mather.find() == true)
        {
            resultado = 0;
            try
            {
                Conexion con = new Conexion();
                Connection conexion = con.getConnection();
                ps = conexion.prepareStatement("update usuario set nombre=?,apellido_paterno=?,apellido_materno=?,contrasena=?,rcontrasena=?,correo_electronico=?,tipo_usuario=? where cusuario=?");
                ps.setString(1, cNombre.getText());
                ps.setString(2, cPaterno.getText());
                ps.setString(3, cMaterno.getText());
                ps.setString(4, cContrasena.getText());
                ps.setString(5, crContrasena.getText());
                ps.setString(6, cCorreo.getText());
                ps.setString(7, comboRol.getSelectedItem().toString());
                ps.setString(8, cUsuario.getText());
                if (cContrasena.getText().equals(crContrasena.getText()))
                {
                    resultado = ps.executeUpdate();

                } else
                {
                    JOptionPane.showMessageDialog(null, "Verifique que las contraseñas sean iguales");
                }

                if ((resultado > 0) && (!"".equals(cUsuario.getText()) && !"".equals(cContrasena.getText())))
                {
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                    limpiar();
                } else
                {
                    JOptionPane.showMessageDialog(null, "No fue posible actualizar los datos");
                }
                conexion.close();
            } catch (Exception e)
            {
                System.err.println(e);
            }
            mostrarTabla();
            limpiar();
            tablaUsuarios.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);

        } else
        {

        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void crContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crContrasenaActionPerformed

    private void cUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUsuarioActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void cCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCorreoActionPerformed

    private void cNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNombreKeyTyped
        if (cNombre.getText().length() >= 30)
        {
            evt.consume();
        }
        char key = evt.getKeyChar();

        if (!Character.isLetter(key) && !(key == KeyEvent.VK_SPACE)
                && !(key == KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        if (cNombre.getText().length() >= 45)
        {
            evt.consume();
        }

        if (evt.getKeyCode() == KeyEvent.VK_TAB)
        {
            cPaterno.setText("");
            evt.consume(); // Evita que el evento Tab se propague
        }
    }//GEN-LAST:event_cNombreKeyTyped

    private void cPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPaternoKeyTyped
        if (cPaterno.getText().length() >= 30)
        {
            evt.consume();
        }
        char key = evt.getKeyChar();

        if (!Character.isLetter(key) && !(key == KeyEvent.VK_SPACE)
                && !(key == KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        if (cPaterno.getText().length() >= 45)
        {
            evt.consume();
        }
     }//GEN-LAST:event_cPaternoKeyTyped

    private void cMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cMaternoKeyTyped
        if (cMaterno.getText().length() >= 30)
        {
            evt.consume();
        }
        char key = evt.getKeyChar();

        if (!Character.isLetter(key) && !(key == KeyEvent.VK_SPACE)
                && !(key == KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        if (cMaterno.getText().length() >= 45)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cMaternoKeyTyped

    public boolean validarContraseña(String contraseña) {
        if (contraseña.length() > 8)
        {
            boolean mayuscula = false;
            boolean numero = false;
            boolean espacio = false;
            char c;

            for (int i = 0; i < contraseña.length(); i++)
            {
                c = contraseña.charAt(i);

                if (Character.isDigit(c))
                {
                    numero = true;
                }

                if (Character.isUpperCase(c))
                {
                    mayuscula = true;
                }

                if (Character.isWhitespace(c))
                {
                    espacio = true;
                }
            }

            return numero && mayuscula && !espacio;
        } else
        {
            return false;
        }
    }

    private void cUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cUsuarioKeyTyped
        if (cUsuario.getText().length() >= 15)
        {
            evt.consume();
        }
        char key = evt.getKeyChar();

        if (!Character.isDigit(key) && !Character.isLetter(key) && !(key == KeyEvent.VK_SPACE)
                && !(key == KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        if (cUsuario.getText().length() >= 45)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cUsuarioKeyTyped

    private void cContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cContrasenaKeyTyped

    }//GEN-LAST:event_cContrasenaKeyTyped

    private void cContrasenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cContrasenaKeyReleased
        // Contraseña de 8-16 caracteres con al menos un dígito, al menos uno
        // letra minúscula, al menos una letra mayúscula, al menos una
        // caracter especial sin espacios en blanco
        String PASSWORD_REGEX = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,12}$";

        Pattern PASSWORD_PATTERN = Pattern.compile(PASSWORD_REGEX);
        // Validar una contraseña
        if (PASSWORD_PATTERN.matcher(cContrasena.getText()).matches())
        {
            lblvalido.setForeground(Color.green);
            lblvalido.setText("Contraseña válida");
        } else
        {
            lblvalido.setForeground(Color.red);
            lblvalido.setText("No cumple con el formato");
        }
    }//GEN-LAST:event_cContrasenaKeyReleased

    private void cNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNombreActionPerformed

    private void cNombreMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cNombreMouseMoved
        // TODO add your handling code here:
        cNombre.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_cNombreMouseMoved

    private void cPaternoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cPaternoMouseMoved
        // TODO add your handling code here:
        cPaterno.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_cPaternoMouseMoved

    private void cUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cUsuarioMouseMoved
        // TODO add your handling code here:
        cUsuario.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_cUsuarioMouseMoved

    private void cContrasenaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cContrasenaMouseMoved
        // TODO add your handling code here:
        // Contraseña de 8-16 caracteres con al menos un dígito, al menos uno
        // letra minúscula, al menos una letra mayúscula, al menos una
        // caracter especial sin espacios en blanco
        cContrasena.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_cContrasenaMouseMoved

    private void crContrasenaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crContrasenaMouseMoved
        // TODO add your handling code here:
        crContrasena.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_crContrasenaMouseMoved

    private void cCorreoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCorreoMouseMoved
        // TODO add your handling code here:
        cCorreo.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_cCorreoMouseMoved

    private void cContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cContrasenaActionPerformed

    private void verContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verContraActionPerformed

    }//GEN-LAST:event_verContraActionPerformed

    private void verContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContraMouseClicked
        // TODO add your handling code here:

        if (!passwordVisible)
        {
            cContrasena.setEchoChar((char) 0); // Muestra el texto sin ocultarlo
            crContrasena.setEchoChar((char) 0);
            passwordVisible = true;
        } else
        {
            cContrasena.setEchoChar('\u2022'); // Oculta el texto con un carácter de viñeta
            crContrasena.setEchoChar('\u2022');
            passwordVisible = false;
        }

    }//GEN-LAST:event_verContraMouseClicked

    private void seleccionarTabla() {
        tablaUsuarios.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                limpiar();
                int row = tablaUsuarios.rowAtPoint(e.getPoint());

                cUsuario.setText(tablaUsuarios.getValueAt(row, 0).toString());
                cNombre.setText(tablaUsuarios.getValueAt(row, 1).toString());
                cPaterno.setText(tablaUsuarios.getValueAt(row, 2).toString());
                cMaterno.setText(tablaUsuarios.getValueAt(row, 3).toString());
                cContrasena.setText(tablaUsuarios.getValueAt(row, 4).toString());
                crContrasena.setText(tablaUsuarios.getValueAt(row, 4).toString());
                cCorreo.setText(tablaUsuarios.getValueAt(row, 5).toString());
                comboRol.setSelectedItem(tablaUsuarios.getValueAt(row, 6).toString());
                botonRegistrar.setEnabled(false);

            }
        });

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPasswordField cContrasena;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cMaterno;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cPaterno;
    private javax.swing.JTextField cUsuario;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JPasswordField crContrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblvalido;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JButton verContra;
    // End of variables declaration//GEN-END:variables
}
